# Generated by Django 2.0.2 on 2018-02-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20180218_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='day_night',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='indoor_outdoor',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
